name: Releases
on: [push]

jobs:   
  release:
    name: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false # This is important if you have branch protection rules!
        
    - name: Import bot's GPG key for signing commits
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true
        
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3 
      id: changelog
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        output-file: "false"
        version-file: './my_custom_version_file.json'
        version-path: 'path.to.version'
        skip-commit: 'false'
        skip-version-file: 'true'
        git-user-name: ${{ steps.import-gpg.outputs.username }}
        git-user-email: ${{ steps.import-gpg.outputs.email }}
        
    - name: Create Release    
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
